trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install

    ng build --configuration=production --verbose

  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  displayName: 'Deploy to Azure Static Web Apps'
  inputs:
    app_location: '/' # Cambia si tu app está en un subdirectorio
    output_location: 'dist/game-app-front/browser' # Cambia si tu build sale en otra carpeta
    azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'
    # El nombre del recurso y la suscripción se toman del recurso vinculado en Azure, no es necesario especificarlos aquí.
